# Generated by Django 4.1.7 on 2023-03-24 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domain',
            old_name='domain_id',
            new_name='domain_url',
        ),
    ]
