# Generated by Django 4.1.7 on 2023-03-24 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_domain_id_domain_domain_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='domain_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
