# Generated by Django 4.1.7 on 2023-03-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_domain_domain_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='active',
            new_name='isactive',
        ),
        migrations.RenameField(
            model_name='historicalarticle',
            old_name='active',
            new_name='isactive',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='active',
            new_name='isisactive',
        ),
        migrations.AddField(
            model_name='domain',
            name='domain_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='isisactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
