# Generated by Django 4.1.7 on 2023-03-24 05:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_article_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_format',
        ),
        migrations.RemoveField(
            model_name='article',
            name='hot',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='article_format',
        ),
        migrations.RemoveField(
            model_name='historicalarticle',
            name='hot',
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='core.writer'),
        ),
        migrations.AlterField(
            model_name='article',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.writer'),
        ),
        migrations.AlterField(
            model_name='domain',
            name='domain_url',
            field=models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='author',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.writer'),
        ),
        migrations.AlterField(
            model_name='historicalarticle',
            name='edited_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='core.writer'),
        ),
    ]
