# Generated by Django 4.1.7 on 2023-03-24 06:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_article_article_format_remove_article_hot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('category', models.CharField(max_length=255)),
                ('url', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('image_url', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('video_url', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.article')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
